// Product catalog for the marketing site: copy ({en,tr}) + accent + docs link
// per product. Imported by product.jsx (product pages), plans.jsx, and home.jsx.
// Technical terms are intentionally kept in English inside the Turkish prose.

const PRODUCTS = {
  core: {
    accent: '#2563eb',
    docs: '/docs/getting-started/introduction',
    related: ['api-security', 'api-discovery', 'gslb', 'waf'],
    en: {
      metaName: 'Elchi Core',
      tag: 'ENVOY MANAGEMENT PLATFORM',
      title1: 'Every Envoy resource.',
      title2: 'One control plane.',
      subtitle: 'The foundation of the Elchi platform: a visual control plane for your entire Envoy fleet — full xDS, multi-version support, safe publish workflows, and a Go edge agent that runs Envoy on your hosts.',
      badges: ['Full xDS Protocol', 'Multi-Version Envoy', 'Go Edge Agent', 'RBAC & Multi-Tenancy'],
      positioning: 'Elchi Core is the base of every deployment. All other Elchi products plug into it as add-ons.',
      caps: [
        { t: 'Complete Envoy resource management', d: 'Listeners, routes, virtual hosts, clusters, endpoints, TLS secrets, filters, extensions, and bootstrap — UI generated from Envoy protobufs with full type-safe validation.' },
        { t: 'Full xDS protocol support', d: 'Complete ADS, CDS, EDS, LDS, RDS, and VHDS implementation on go-control-plane, with delta xDS for efficient incremental updates.' },
        { t: 'Multi-version fleet', d: 'Run several Envoy versions side by side with per-version control-planes. Migrate resources across versions with automated compatibility checks.' },
        { t: 'Save & publish workflow', d: 'Draft changes safely, validate twice (TypeScript frontend + protoc-gen-validate backend), publish atomically, and roll back when needed.' },
        { t: 'Edge agent (elchi-client)', d: 'Installs and supervises Envoy as systemd services with hot-restart zero-downtime upgrades, BGP/FRR routing, netplan networking, and log shipping.' },
        { t: 'Dependency graph & route map', d: 'Interactive visualizations of resource relationships and route-to-cluster paths for fast troubleshooting.' },
        { t: 'Scenarios, templates & snippets', d: 'Guided multi-resource wizards and a reusable config library for API gateways, load balancers, and mesh setups.' },
        { t: 'Multi-project & RBAC', d: 'Project-based isolation with 4-tier roles (Owner, Admin, Editor, Viewer), LDAP/Active Directory, 2FA, and a complete audit trail.' },
        { t: 'Observability built in', d: 'Metrics dashboards, live service logs, Grafana integration, and an async job engine with full visibility into long-running operations.' },
      ],
      also: {
        title: 'Also included in Core',
        items: ['ACME certificates (Let\'s Encrypt & Google Trust, DNS-01)', 'Kubernetes endpoint discovery', 'AI-assisted config & log analysis', 'Threat intelligence & GeoIP enrichment', 'Registry HA & leader election', 'Backup, restore & maintenance tooling'],
      },
      flow: {
        title: 'How it works',
        steps: [
          { t: 'Configure', d: 'Build resources in visual editors generated from Envoy protos.' },
          { t: 'Validate', d: 'Two-step validation catches errors before anything ships.' },
          { t: 'Publish', d: 'Atomic xDS push to every subscribed Envoy — with rollback.' },
          { t: 'Operate', d: 'The agent upgrades, monitors, and heals your edge fleet.' },
        ],
      },
    },
    tr: {
      metaName: 'Elchi Core',
      tag: 'ENVOY YÖNETİM PLATFORMU',
      title1: 'Tüm Envoy kaynakları.',
      title2: 'Tek control plane.',
      subtitle: 'Elchi platformunun temeli: tüm Envoy filonuz için görsel bir control plane — tam xDS, çoklu sürüm desteği, güvenli yayınlama iş akışları ve Envoy\'u sunucularınızda çalıştıran Go tabanlı edge agent.',
      badges: ['Tam xDS Protokolü', 'Çok Sürümlü Envoy', 'Go Edge Agent', 'RBAC & Çok Kiracılılık'],
      positioning: 'Elchi Core her kurulumun temelidir. Diğer tüm Elchi ürünleri ona eklenti (add-on) olarak bağlanır.',
      caps: [
        { t: 'Eksiksiz Envoy kaynak yönetimi', d: 'Listener, route, virtual host, cluster, endpoint, TLS secret, filter, extension ve bootstrap — Envoy protobuf\'larından üretilen arayüz ve tam tip güvenli doğrulama.' },
        { t: 'Tam xDS protokol desteği', d: 'go-control-plane üzerinde eksiksiz ADS, CDS, EDS, LDS, RDS ve VHDS; verimli artımlı güncellemeler için delta xDS.' },
        { t: 'Çok sürümlü filo', d: 'Birden fazla Envoy sürümünü sürüm başına control-plane\'lerle yan yana çalıştırın. Kaynakları otomatik uyumluluk kontrolleriyle sürümler arası taşıyın.' },
        { t: 'Kaydet & yayınla iş akışı', d: 'Değişiklikleri taslakta güvenle hazırlayın, iki kez doğrulayın (TypeScript frontend + protoc-gen-validate backend), atomik yayınlayın, gerekirse geri alın.' },
        { t: 'Edge agent (elchi-client)', d: 'Envoy\'u systemd servisi olarak kurar ve yönetir: hot-restart ile kesintisiz yükseltme, BGP/FRR, netplan ağ yönetimi ve log aktarımı.' },
        { t: 'Bağımlılık grafiği & route haritası', d: 'Kaynak ilişkilerinin ve route-cluster yollarının etkileşimli görselleştirmesiyle hızlı sorun giderme.' },
        { t: 'Senaryolar, şablonlar & snippet\'ler', d: 'API gateway, load balancer ve mesh kurulumları için rehberli sihirbazlar ve yeniden kullanılabilir yapılandırma kütüphanesi.' },
        { t: 'Çoklu proje & RBAC', d: '4 katmanlı roller (Owner, Admin, Editor, Viewer), LDAP/Active Directory, 2FA ve eksiksiz denetim iziyle proje bazlı izolasyon.' },
        { t: 'Yerleşik gözlemlenebilirlik', d: 'Metrik panoları, canlı servis logları, Grafana entegrasyonu ve uzun süren işlemleri tam görünürlükle izleyen asenkron iş motoru.' },
      ],
      also: {
        title: 'Core\'a dahil diğer yetenekler',
        items: ['ACME sertifikaları (Let\'s Encrypt & Google Trust, DNS-01)', 'Kubernetes endpoint keşfi', 'AI destekli yapılandırma & log analizi', 'Tehdit istihbaratı & GeoIP zenginleştirme', 'Registry HA & leader election', 'Yedekleme, geri yükleme & bakım araçları'],
      },
      flow: {
        title: 'Nasıl çalışır',
        steps: [
          { t: 'Yapılandır', d: 'Envoy proto\'larından üretilen görsel editörlerle kaynakları oluşturun.' },
          { t: 'Doğrula', d: 'İki aşamalı doğrulama hataları yayına çıkmadan yakalar.' },
          { t: 'Yayınla', d: 'Abone tüm Envoy\'lara atomik xDS gönderimi — geri almalı.' },
          { t: 'İşlet', d: 'Agent edge filonuzu yükseltir, izler ve ayakta tutar.' },
        ],
      },
    },
  },

  'api-security': {
    accent: '#f43f5e',
    docs: '/docs/shield/overview',
    related: ['api-discovery', 'waf'],
    en: {
      metaName: 'Elchi API Security',
      tag: 'POWERED BY SHIELD',
      title1: 'API security, enforced',
      title2: 'at the edge.',
      subtitle: 'Shield is an ext_proc engine running next to each Envoy: authentication, rate limiting, bot defense, data-loss prevention, and a built-in OWASP CRS WAF — composed per route and rolled out safely from detect to block.',
      badges: ['12 Security Engines', 'Built-in DLP', 'OWASP CRS WAF', 'Detect → Shadow → Block'],
      positioning: 'Add-on to Elchi Core. Deployed and configured centrally, enforced locally on every edge host — traffic never leaves the box.',
      caps: [
        { t: 'Authentication engines', d: 'JWT and JWKS (remote keys refreshed in the background), API keys with SHA-256 hashing and scopes, HMAC request signing including RFC 9421, and mTLS client-certificate checks.' },
        { t: 'Rate limiting', d: 'Token-bucket limits keyed by IP, host, or any header — requests per second plus burst, per route.' },
        { t: 'Bot & scanner defense', d: 'Layered scoring over User-Agent heuristics, verified-crawler feeds, JA3/JA4 TLS fingerprints, and header-anomaly detection.' },
        { t: 'IP reputation & GeoIP', d: 'Threat-intel feeds with severity, static CIDR allow/deny lists, and country or ASN blocking backed by MaxMind databases.' },
        { t: 'DLP & redaction', d: 'Detects credit cards (Luhn-validated), SSNs, JWTs, cloud keys, and tokens in requests and responses — block the call or mask the data in place.' },
        { t: 'Built-in WAF', d: 'Coraza engine with the OWASP Core Rule Set embedded in the binary: paranoia levels, anomaly thresholds, and per-policy rule exclusions.' },
        { t: 'GraphQL & OpenAPI guard', d: 'Depth, complexity, and introspection limits for GraphQL; positive-security validation against your OpenAPI spec.' },
        { t: 'Safe rollout', d: 'Per-policy block / detect / shadow modes with fail-open or fail-close behavior, path excludes, and sampling — promote confidently.' },
        { t: 'Forensics & telemetry', d: 'Redacted-by-construction audit events streamed to ClickHouse or OpenTelemetry, a live event feed in the UI, and Prometheus metrics.' },
      ],
      flow: {
        title: 'From discovery to enforcement',
        steps: [
          { t: 'Discover', d: 'Import endpoints and risks straight from API Discovery.' },
          { t: 'Compose', d: 'Build policies per domain and route in the visual builder.' },
          { t: 'Roll out', d: 'Start in detect, verify in shadow, then switch to block.' },
          { t: 'Watch', d: 'Follow verdicts live in the security event feed.' },
        ],
      },
    },
    tr: {
      metaName: 'Elchi API Security',
      tag: 'SHIELD İLE GÜÇLENDİRİLDİ',
      title1: 'API güvenliği,',
      title2: 'edge\'de uygulanır.',
      subtitle: 'Shield, her Envoy\'un yanında çalışan bir ext_proc motorudur: kimlik doğrulama, rate limiting, bot savunması, veri sızıntısı önleme ve yerleşik OWASP CRS WAF — route başına birleştirilir, detect\'ten block\'a güvenle yayılır.',
      badges: ['12 Güvenlik Engine\'i', 'Yerleşik DLP', 'OWASP CRS WAF', 'Detect → Shadow → Block'],
      positioning: 'Elchi Core eklentisidir. Merkezden dağıtılır ve yönetilir, her edge sunucuda yerel olarak uygulanır — trafik makineden dışarı çıkmaz.',
      caps: [
        { t: 'Kimlik doğrulama engine\'leri', d: 'JWT ve JWKS (uzak anahtarlar arka planda yenilenir), SHA-256 ile saklanan scope\'lu API key\'ler, RFC 9421 dahil HMAC istek imzalama ve mTLS istemci sertifikası kontrolleri.' },
        { t: 'Rate limiting', d: 'IP, host veya herhangi bir header\'a göre anahtarlanan token-bucket limitleri — route başına saniyelik istek + burst.' },
        { t: 'Bot & tarayıcı savunması', d: 'User-Agent sezgileri, doğrulanmış crawler beslemeleri, JA3/JA4 TLS parmak izleri ve header anomali tespiti üzerinde katmanlı puanlama.' },
        { t: 'IP itibarı & GeoIP', d: 'Önem dereceli tehdit istihbaratı beslemeleri, statik CIDR izin/engel listeleri ve MaxMind destekli ülke veya ASN engelleme.' },
        { t: 'DLP & maskeleme', d: 'İstek ve yanıtlarda kredi kartı (Luhn doğrulamalı), SSN, JWT, bulut anahtarları ve token tespiti — çağrıyı engelleyin ya da veriyi yerinde maskeleyin.' },
        { t: 'Yerleşik WAF', d: 'Binary\'ye gömülü OWASP Core Rule Set ile Coraza motoru: paranoya seviyeleri, anomali eşikleri ve policy başına kural istisnaları.' },
        { t: 'GraphQL & OpenAPI koruması', d: 'GraphQL için derinlik, karmaşıklık ve introspection sınırları; OpenAPI spesifikasyonunuza karşı pozitif güvenlik doğrulaması.' },
        { t: 'Güvenli yayılım', d: 'Policy başına block / detect / shadow modları, fail-open veya fail-close davranışı, path istisnaları ve örnekleme — güvenle terfi ettirin.' },
        { t: 'Adli kayıt & telemetri', d: 'Tasarımı gereği maskelenmiş denetim olayları ClickHouse veya OpenTelemetry\'ye akar; arayüzde canlı olay akışı, Prometheus metrikleri.' },
      ],
      flow: {
        title: 'Keşiften uygulamaya',
        steps: [
          { t: 'Keşfet', d: 'Endpoint\'leri ve riskleri doğrudan API Discovery\'den içe aktarın.' },
          { t: 'Birleştir', d: 'Görsel builder\'da domain ve route başına policy kurun.' },
          { t: 'Yay', d: 'Detect\'te başlayın, shadow\'da doğrulayın, block\'a geçin.' },
          { t: 'İzle', d: 'Kararları canlı güvenlik olay akışından takip edin.' },
        ],
      },
    },
  },

  'api-discovery': {
    accent: '#6366f1',
    docs: '/docs/api-discovery/overview',
    related: ['api-security'],
    en: {
      metaName: 'Elchi API Discovery',
      tag: 'API INVENTORY & POSTURE',
      title1: 'Know every API',
      title2: 'you actually expose.',
      subtitle: 'Turns live Envoy traffic into a continuously scored API inventory: shadow endpoints, missing auth, PII exposure, drift — with a one-click path from finding to protection.',
      badges: ['Zero Instrumentation', 'A–F Security Score', 'OpenAPI 3.0.3 Export', 'Drift Detection'],
      positioning: 'Add-on to Elchi Core. Built from Envoy access-log streams — no SDKs, no code changes, no traffic interception.',
      caps: [
        { t: 'Traffic-based discovery', d: 'The inventory is built from Envoy access-log (ALS) streams. Smart path normalization turns IDs, UUIDs, and tokens into {placeholders}; gRPC methods are parsed natively.' },
        { t: 'Attack surface separation', d: 'Confirmed, real APIs are kept apart from scanner and probe noise — so your catalog stays clean while you still see what attackers are trying.' },
        { t: 'Auth coverage', d: 'Every endpoint is tagged with its observed auth schemes (JWT, mTLS, API key, none) — unauthenticated and inconsistently-authenticated surfaces stand out immediately.' },
        { t: 'PII inventory', d: 'Know which endpoints carry personal data, by category, before an auditor or an incident tells you.' },
        { t: 'Risk flags & scoring', d: 'Stateful detectors flag BOLA patterns, brute force, weak TLS, and more. Each endpoint gets a risk score; the whole surface gets an A–F grade.' },
        { t: 'Drift & change detection', d: 'Snapshot baselines and diff the live inventory against them. Catch new, changed, and zombie endpoints automatically.' },
        { t: 'Consumer & traffic analytics', d: 'Per-consumer behavior, bot and scanner heatmaps, and geo / ASN / threat-intel aggregates across your API estate.' },
        { t: 'OpenAPI 3.0.3 export', d: 'Generate an OpenAPI spec from confirmed endpoints — paths, parameters, methods, status codes, and auth schemes reconstructed from real traffic.' },
        { t: 'One-click protection', d: 'Turn findings into a draft Elchi API Security policy: matching engines are pre-selected per endpoint with the rationale attached.' },
      ],
      flow: {
        title: 'How it works',
        steps: [
          { t: 'Observe', d: 'Envoy streams access logs to the collector.' },
          { t: 'Normalize', d: 'Paths are normalized, enriched with GeoIP and threat intel.' },
          { t: 'Score', d: 'Detectors flag risk; endpoints and estate get graded.' },
          { t: 'Act', d: 'Export OpenAPI or generate a Shield policy draft.' },
        ],
      },
    },
    tr: {
      metaName: 'Elchi API Discovery',
      tag: 'API ENVANTERİ & GÜVENLİK DURUŞU',
      title1: 'Gerçekte sunduğunuz',
      title2: 'her API\'yi bilin.',
      subtitle: 'Canlı Envoy trafiğini sürekli puanlanan bir API envanterine dönüştürür: shadow endpoint\'ler, eksik kimlik doğrulama, PII maruziyeti, sapma — ve bulgudan korumaya tek tıkla giden yol.',
      badges: ['Sıfır Enstrümantasyon', 'A–F Güvenlik Notu', 'OpenAPI 3.0.3 Dışa Aktarım', 'Sapma Tespiti'],
      positioning: 'Elchi Core eklentisidir. Envoy access-log akışlarından beslenir — SDK yok, kod değişikliği yok, trafiğe müdahale yok.',
      caps: [
        { t: 'Trafik tabanlı keşif', d: 'Envanter Envoy access-log (ALS) akışlarından oluşur. Akıllı path normalizasyonu ID, UUID ve token\'ları {placeholder}\'lara çevirir; gRPC metodları doğal olarak ayrıştırılır.' },
        { t: 'Saldırı yüzeyi ayrımı', d: 'Doğrulanmış gerçek API\'ler, tarayıcı ve probe gürültüsünden ayrı tutulur — katalogunuz temiz kalır, saldırganların ne denediğini yine de görürsünüz.' },
        { t: 'Kimlik doğrulama kapsamı', d: 'Her endpoint gözlemlenen auth şemalarıyla etiketlenir (JWT, mTLS, API key, yok) — doğrulamasız ve tutarsız doğrulamalı yüzeyler anında öne çıkar.' },
        { t: 'PII envanteri', d: 'Hangi endpoint\'in hangi kategoride kişisel veri taşıdığını, bir denetçi ya da olay söylemeden önce bilin.' },
        { t: 'Risk bayrakları & puanlama', d: 'Durum bilgili dedektörler BOLA örüntülerini, brute force\'u, zayıf TLS\'i ve fazlasını işaretler. Her endpoint risk puanı, tüm yüzey A–F notu alır.' },
        { t: 'Sapma & değişiklik tespiti', d: 'Temel snapshot\'lar alın ve canlı envanteri onlarla karşılaştırın. Yeni, değişen ve zombie endpoint\'leri otomatik yakalayın.' },
        { t: 'Tüketici & trafik analitiği', d: 'Tüketici bazlı davranış, bot ve tarayıcı ısı haritaları, tüm API varlığınızda geo / ASN / tehdit istihbaratı toplamları.' },
        { t: 'OpenAPI 3.0.3 dışa aktarımı', d: 'Doğrulanmış endpoint\'lerden OpenAPI spesifikasyonu üretin — path\'ler, parametreler, metodlar, durum kodları ve auth şemaları gerçek trafikten çıkarılır.' },
        { t: 'Tek tıkla koruma', d: 'Bulguları taslak bir Elchi API Security policy\'sine dönüştürün: uygun engine\'ler endpoint başına, gerekçesiyle birlikte önceden seçilir.' },
      ],
      flow: {
        title: 'Nasıl çalışır',
        steps: [
          { t: 'Gözlemle', d: 'Envoy, access loglarını collector\'a akıtır.' },
          { t: 'Normalize et', d: 'Path\'ler normalize edilir; GeoIP ve tehdit istihbaratıyla zenginleşir.' },
          { t: 'Puanla', d: 'Dedektörler riski işaretler; endpoint\'ler ve yüzey notlanır.' },
          { t: 'Harekete geç', d: 'OpenAPI dışa aktarın ya da Shield policy taslağı üretin.' },
        ],
      },
    },
  },

  gslb: {
    accent: '#f59e0b',
    docs: '/docs/gslb/overview',
    related: ['core'],
    en: {
      metaName: 'Elchi GSLB',
      tag: 'GLOBAL SERVER LOAD BALANCING',
      title1: 'DNS that follows',
      title2: 'your health.',
      subtitle: 'CoreDNS-based authoritative DNS driven by distributed health checking: geo routing, per-record failover zones, and anti-flapping state machines — at 100K+ endpoint scale.',
      badges: ['CoreDNS Authoritative', 'HTTP/HTTPS/TCP Probes', 'Geo Routing', '100K+ IPs'],
      positioning: 'Add-on to Elchi Core. Health state lives in the platform; CoreDNS nodes serve answers from versioned snapshots.',
      caps: [
        { t: 'Authoritative DNS via CoreDNS', d: 'GSLB nodes pull versioned zone snapshots (with incremental change feeds) over a per-zone secret-authenticated API and answer authoritatively.' },
        { t: 'Health probes everywhere', d: 'HTTP, HTTPS, and TCP probes with custom Host headers and skip-TLS-verify options; intervals tunable from 10 seconds to 5 minutes.' },
        { t: 'Anti-flapping state machine', d: 'A quad-state model (PASSING → WARNING → CRITICAL → RECOVERY) with configurable thresholds keeps unstable endpoints from bouncing in and out of DNS.' },
        { t: 'Failover zones', d: 'When every IP behind a record is unhealthy, DNS answers with the record\'s failover FQDN — automatic CNAME fallback to a backup zone.' },
        { t: 'Geo / region routing', d: 'Tag IPs with regions and serve region-filtered answers, so users land on the closest healthy endpoint.' },
        { t: 'Circuit-breaker probing', d: 'Failing IPs back off gradually (10s → 120s) instead of hammering dead hosts; state transitions trigger immediate re-probes.' },
        { t: 'Record & IP management', d: 'Full CRUD with bulk operations, manual health overrides, per-IP history, and IPs auto-generated from service deployments.' },
        { t: 'Built for scale & HA', d: 'Sharded health storage, MongoDB leader-election leases, and automatic rebalancing when a controller fails — proven past 100K IPs.' },
      ],
      flow: {
        title: 'How it works',
        steps: [
          { t: 'Define', d: 'Create records and attach IPs — manually or from services.' },
          { t: 'Probe', d: 'Distributed workers health-check every IP continuously.' },
          { t: 'Serve', d: 'CoreDNS answers with only healthy, region-matched IPs.' },
          { t: 'Fail over', d: 'Empty pools fall back to backup zones automatically.' },
        ],
      },
    },
    tr: {
      metaName: 'Elchi GSLB',
      tag: 'GLOBAL SERVER LOAD BALANCING',
      title1: 'Sağlık durumunu izleyen',
      title2: 'DNS.',
      subtitle: 'Dağıtık sağlık kontrolünün beslediği CoreDNS tabanlı yetkili DNS: coğrafi yönlendirme, kayıt başına failover bölgeleri ve anti-flapping durum makineleri — 100K+ endpoint ölçeğinde.',
      badges: ['CoreDNS Yetkili DNS', 'HTTP/HTTPS/TCP Probları', 'Coğrafi Yönlendirme', '100K+ IP'],
      positioning: 'Elchi Core eklentisidir. Sağlık durumu platformda tutulur; CoreDNS düğümleri sürümlü snapshot\'lardan yanıt verir.',
      caps: [
        { t: 'CoreDNS ile yetkili DNS', d: 'GSLB düğümleri, bölge başına secret ile doğrulanan API üzerinden sürümlü zone snapshot\'larını (artımlı değişiklik akışıyla) çeker ve yetkili yanıt verir.' },
        { t: 'Her yerde sağlık probu', d: 'Özel Host header ve TLS doğrulama atlama seçenekleriyle HTTP, HTTPS ve TCP probları; 10 saniyeden 5 dakikaya ayarlanabilir aralıklar.' },
        { t: 'Anti-flapping durum makinesi', d: 'Ayarlanabilir eşikli dörtlü durum modeli (PASSING → WARNING → CRITICAL → RECOVERY), kararsız endpoint\'lerin DNS\'e girip çıkmasını engeller.' },
        { t: 'Failover bölgeleri', d: 'Bir kaydın arkasındaki tüm IP\'ler sağlıksızsa DNS, kaydın failover FQDN\'iyle yanıt verir — yedek bölgeye otomatik CNAME geçişi.' },
        { t: 'Coğrafi / bölgesel yönlendirme', d: 'IP\'leri bölgelerle etiketleyin, bölge filtreli yanıtlar sunun — kullanıcılar en yakın sağlıklı endpoint\'e ulaşsın.' },
        { t: 'Circuit-breaker\'lı problama', d: 'Başarısız IP\'lerde prob aralığı kademeli artar (10sn → 120sn), ölü sunucular boşuna yoklanmaz; durum geçişleri anında yeniden prob tetikler.' },
        { t: 'Kayıt & IP yönetimi', d: 'Toplu işlemli tam CRUD, manuel sağlık geçersiz kılma, IP başına geçmiş ve servis dağıtımlarından otomatik üretilen IP\'ler.' },
        { t: 'Ölçek & HA için tasarlandı', d: 'Parçalı (sharded) sağlık deposu, MongoDB leader-election kiraları ve controller arızasında otomatik yeniden dengeleme — 100K+ IP\'de kanıtlanmış.' },
      ],
      flow: {
        title: 'Nasıl çalışır',
        steps: [
          { t: 'Tanımla', d: 'Kayıtları oluşturun, IP\'leri elle ya da servislerden bağlayın.' },
          { t: 'Probla', d: 'Dağıtık işçiler her IP\'yi sürekli sağlık kontrolünden geçirir.' },
          { t: 'Yanıtla', d: 'CoreDNS yalnızca sağlıklı, bölgeye uygun IP\'lerle yanıt verir.' },
          { t: 'Devret', d: 'Boş havuzlar otomatik olarak yedek bölgelere düşer.' },
        ],
      },
    },
  },

  waf: {
    accent: '#8b5cf6',
    docs: '/docs/waf/overview',
    related: ['api-security'],
    en: {
      metaName: 'Elchi WAF',
      tag: 'WASM WEB APPLICATION FIREWALL',
      title1: 'OWASP CRS,',
      title2: 'inside your Envoy.',
      subtitle: 'A Coraza-based WAF deployed as an in-process Envoy WASM filter: versioned rule configs, a full CRS browser, per-domain directives — managed centrally, delivered to the edge, no sidecar required.',
      badges: ['Coraza + OWASP CRS', 'In-Process WASM', 'Versioned Configs', 'SHA-256 Verified'],
      positioning: 'Add-on to Elchi Core. The lightest way to put OWASP CRS in front of your services — one filter in the Envoy chain, zero extra processes.',
      caps: [
        { t: 'In-process WASM filter', d: 'The coraza.wasm module loads directly into the Envoy filter chain — no sidecar, no extra process, no additional hop on the host.' },
        { t: 'OWASP Core Rule Set', d: 'Browse CRS rules by version, severity, phase, and paranoia level; pick rule sets and import exactly what you need.' },
        { t: 'Custom directives', d: 'Per-domain and per-authority directive sets on top of CRS — tune the WAF to each application it protects.' },
        { t: 'Config versioning & restore', d: 'Every WAF config change is versioned with full history and one-click restore.' },
        { t: 'Central management, edge delivery', d: 'Configs are built in the UI, injected into the Envoy WASM extension, and delivered by the edge agent with SHA-256-verified module downloads.' },
        { t: 'Module version control', d: 'Multiple coraza.wasm versions are retained per host; switch the active version per deployment, with rollback.' },
      ],
      versus: {
        title: 'WAF, two ways',
        subtitle: 'Elchi ships Coraza in two deployment models. Pick per workload — or run both.',
        colA: 'Elchi WAF (this product)',
        colB: 'WAF inside Elchi API Security',
        rows: [
          ['Runs as an in-process Envoy WASM filter', 'Runs inside the Shield ext_proc engine'],
          ['Lightest footprint — no extra process', 'One pipeline with auth, DLP, bot defense & rate limiting'],
          ['CRS + custom directives, versioned configs', 'CRS embedded in the Shield binary, tuned per policy'],
          ['Best for: standalone L7 protection', 'Best for: full API-security enforcement per route'],
        ],
      },
      flow: {
        title: 'How it works',
        steps: [
          { t: 'Compose', d: 'Pick CRS rules and directives in the WAF studio.' },
          { t: 'Version', d: 'Every change is recorded; restore any prior config.' },
          { t: 'Deliver', d: 'The agent ships the verified WASM module to each host.' },
          { t: 'Enforce', d: 'Envoy filters traffic in-process — no detours.' },
        ],
      },
    },
    tr: {
      metaName: 'Elchi WAF',
      tag: 'WASM WEB APPLICATION FIREWALL',
      title1: 'OWASP CRS,',
      title2: 'Envoy\'unuzun içinde.',
      subtitle: 'In-process Envoy WASM filtresi olarak dağıtılan Coraza tabanlı WAF: sürümlü kural yapılandırmaları, tam CRS tarayıcısı, domain başına direktifler — merkezden yönetilir, edge\'e dağıtılır, sidecar gerekmez.',
      badges: ['Coraza + OWASP CRS', 'In-Process WASM', 'Sürümlü Yapılandırma', 'SHA-256 Doğrulamalı'],
      positioning: 'Elchi Core eklentisidir. Servislerinizin önüne OWASP CRS koymanın en hafif yolu — Envoy zincirinde tek filtre, sıfır ek süreç.',
      caps: [
        { t: 'In-process WASM filtresi', d: 'coraza.wasm modülü doğrudan Envoy filtre zincirine yüklenir — sidecar yok, ek süreç yok, sunucuda ek atlama yok.' },
        { t: 'OWASP Core Rule Set', d: 'CRS kurallarını sürüme, önem derecesine, faza ve paranoya seviyesine göre inceleyin; kural setlerini seçin, tam ihtiyacınızı içe aktarın.' },
        { t: 'Özel direktifler', d: 'CRS\'in üzerine domain ve authority başına direktif setleri — WAF\'ı koruduğu her uygulamaya göre ayarlayın.' },
        { t: 'Yapılandırma sürümleme & geri yükleme', d: 'Her WAF yapılandırma değişikliği tam geçmişle sürümlenir; tek tıkla geri yükleyin.' },
        { t: 'Merkezi yönetim, edge\'e dağıtım', d: 'Yapılandırmalar arayüzde kurulur, Envoy WASM extension\'ına enjekte edilir ve SHA-256 doğrulamalı modül indirmeleriyle edge agent tarafından dağıtılır.' },
        { t: 'Modül sürüm kontrolü', d: 'Sunucu başına birden fazla coraza.wasm sürümü saklanır; aktif sürümü dağıtım başına değiştirin, geri alın.' },
      ],
      versus: {
        title: 'İki farklı WAF modeli',
        subtitle: 'Elchi, Coraza\'yı iki dağıtım modeliyle sunar. İş yüküne göre seçin — ya da ikisini birlikte çalıştırın.',
        colA: 'Elchi WAF (bu ürün)',
        colB: 'Elchi API Security içindeki WAF',
        rows: [
          ['In-process Envoy WASM filtresi olarak çalışır', 'Shield ext_proc motorunun içinde çalışır'],
          ['En hafif ayak izi — ek süreç yok', 'Auth, DLP, bot savunması ve rate limiting ile tek pipeline'],
          ['CRS + özel direktifler, sürümlü yapılandırmalar', 'CRS Shield binary\'sine gömülü, policy başına ayarlanır'],
          ['En uygun: bağımsız L7 koruması', 'En uygun: route başına eksiksiz API güvenliği'],
        ],
      },
      flow: {
        title: 'Nasıl çalışır',
        steps: [
          { t: 'Kur', d: 'WAF studio\'da CRS kurallarını ve direktifleri seçin.' },
          { t: 'Sürümle', d: 'Her değişiklik kaydedilir; önceki yapılandırmaya dönün.' },
          { t: 'Dağıt', d: 'Agent, doğrulanmış WASM modülünü her sunucuya taşır.' },
          { t: 'Uygula', d: 'Envoy trafiği in-process filtreler — dolambaç yok.' },
        ],
      },
    },
  },
};

export { PRODUCTS };
