// Product screenshots: one entry per screen, each captured in the light and
// the dark theme as /shots/<id>-light.webp and /shots/<id>-dark.webp (from a
// live demo environment: real Envoy traffic, Shield blocks, API discovery).
// Used by the home gallery and the product pages (products-data.js `shots`).

export const SHOT_CATS = {
  en: { all: 'All', overview: 'Overview', config: 'Configuration', observe: 'Observability', security: 'Security', discovery: 'API Discovery', fleet: 'Fleet & Operations', viz: 'Visualization', lb: 'Load Balancing', ai: 'AI' },
  tr: { all: 'Tümü', overview: 'Genel Bakış', config: 'Yapılandırma', observe: 'Gözlemlenebilirlik', security: 'Güvenlik', discovery: 'API Keşfi', fleet: 'Filo & Operasyon', viz: 'Görselleştirme', lb: 'Yük Dengeleme', ai: 'AI' },
};

export const SHOTS = [
  { id: 'dashboard', cat: 'overview',
    en: ['Command Center', 'Live requests, errors, connections and Shield activity for the whole project at a glance.'],
    tr: ['Komuta Merkezi', 'Projenin tamamı için canlı istek, hata, bağlantı ve Shield aktivitesi tek bakışta.'] },
  { id: 'services', cat: 'fleet',
    en: ['Services', 'Every managed Envoy service with its version, deployment state, addresses and admin port.'],
    tr: ['Servisler', 'Yönetilen her Envoy servisi; sürüm, deploy durumu, adresler ve admin port ile.'] },
  { id: 'service-detail', cat: 'fleet',
    en: ['Service Operations', 'Deploy, restart, upgrade and inspect a service on each edge client — live status per host.'],
    tr: ['Servis Operasyonları', 'Bir servisi her edge client üzerinde deploy edin, yeniden başlatın, yükseltin ve inceleyin.'] },
  { id: 'listener', cat: 'config',
    en: ['xDS Configuration', 'Editors generated from Envoy protobufs — here an HTTP connection manager with Shield and API discovery on.'],
    tr: ['xDS Yapılandırması', 'Envoy protobuf’larından üretilen editörler — burada Shield ve API keşfi açık bir HTTP connection manager.'] },
  { id: 'filters', cat: 'config',
    en: ['HTTP Filters', 'Reusable filter configs delivered through ECDS, shared across listeners and versions.'],
    tr: ['HTTP Filtreleri', 'ECDS ile dağıtılan, listener ve sürümler arasında paylaşılan yeniden kullanılabilir filtreler.'] },
  { id: 'scenarios', cat: 'config',
    en: ['Scenarios', 'Guided wizards that create a complete service — listener, HCM, routes, clusters — in one go.'],
    tr: ['Senaryolar', 'Listener, HCM, route ve cluster’larıyla eksiksiz bir servisi tek seferde oluşturan sihirbazlar.'] },
  { id: 'metrics', cat: 'observe',
    en: ['Metrics', 'Per-service dashboards with change markers, compare, per-client split and a cluster table.'],
    tr: ['Metrikler', 'Değişiklik işaretleri, karşılaştırma, client kırılımı ve cluster tablosu ile servis dashboard’ları.'] },
  { id: 'metrics-explore', cat: 'observe',
    en: ['Metrics Explore', 'Any stat Envoy reports, charted with the right math — several at once with a shared crosshair.'],
    tr: ['Metrik Keşfi', 'Envoy’un raporladığı her stat doğru hesapla; birden fazlası ortak imleçle yan yana.'] },
  { id: 'logs', cat: 'observe',
    en: ['Service Logs', 'Envoy access and error logs from every client, searchable, with a request detail view.'],
    tr: ['Servis Logları', 'Her client’tan Envoy access ve error logları; aranabilir, istek detay görünümüyle.'] },
  { id: 'shield-overview', cat: 'security',
    en: ['Shield Overview', 'Inspected and blocked requests per second, the blocked share and Shield’s own latency per phase.'],
    tr: ['Shield Genel Bakış', 'Saniyede incelenen ve engellenen istekler, engellenen pay ve Shield’ın faz bazında kendi gecikmesi.'] },
  { id: 'shield-events', cat: 'security',
    en: ['Security Events', 'Every block with its engine, rule, request and reason — WAF, bot, API key, rate limit — and the top engines.'],
    tr: ['Güvenlik Olayları', 'Her engelleme motoru, kuralı, isteği ve nedeniyle — WAF, bot, API key, rate limit — ve en çok tetiklenen motorlar.'] },
  { id: 'shield-policy', cat: 'security',
    en: ['Shield Policies', 'Policy-as-code with per-route engines, validated and synced to every client.'],
    tr: ['Shield Politikaları', 'Route bazlı motorlarla policy-as-code; doğrulanır ve her client’a senkronlanır.'] },
  { id: 'api-discovery', cat: 'discovery',
    en: ['API Discovery', 'The API surface learned from live traffic: listeners, endpoints, risk and activity.'],
    tr: ['API Keşfi', 'Canlı trafikten öğrenilen API yüzeyi: listener’lar, endpoint’ler, risk ve aktivite.'] },
  { id: 'api-endpoints', cat: 'discovery',
    en: ['API Inventory', 'Normalized endpoints with methods, status mix, latency, auth and PII observations.'],
    tr: ['API Envanteri', 'Method, status dağılımı, gecikme, auth ve PII gözlemleriyle normalize edilmiş endpoint’ler.'] },
  { id: 'dependency', cat: 'viz',
    en: ['Dependency Graph', 'How a service’s resources reference each other, from listener to endpoints.'],
    tr: ['Bağımlılık Grafiği', 'Bir servisin kaynaklarının listener’dan endpoint’lere birbirine nasıl bağlandığı.'] },
  { id: 'routemap', cat: 'viz',
    en: ['Route Map', 'Virtual hosts, routes and the clusters they send traffic to, as one map.'],
    tr: ['Route Haritası', 'Virtual host’lar, route’lar ve trafiği gönderdikleri cluster’lar tek haritada.'] },
  { id: 'clients', cat: 'fleet',
    en: ['Edge Clients', 'The agents running Envoy on your hosts: CPU, memory, connections, storage and network per host.'],
    tr: ['Edge Client’lar', 'Envoy’u host’larınızda çalıştıran agent’lar: host başına CPU, bellek, bağlantı, disk ve ağ.'] },
  { id: 'registry', cat: 'fleet',
    en: ['Registry', 'Control planes and controllers, leader election and which client is served where.'],
    tr: ['Registry', 'Control plane ve controller’lar, lider seçimi ve hangi client’ın nereden servis aldığı.'] },
  { id: 'audit', cat: 'security',
    en: ['Audit Trail', 'Who changed what and when — every API call, deploy and publish, with the field-level diff.'],
    tr: ['Denetim İzi', 'Kim neyi ne zaman değiştirdi — her API çağrısı, deploy ve publish, alan düzeyinde farkıyla.'] },
  { id: 'jobs', cat: 'fleet',
    en: ['Background Jobs', 'Long-running operations with progress, per-client results and history.'],
    tr: ['Arka Plan İşleri', 'Uzun süren işlemler; ilerleme, client bazlı sonuçlar ve geçmiş ile.'] },
  { id: 'ai-analyzer', cat: 'ai',
    en: ['AI Analyzer', 'Pick a resource and ask about it — the analysis gets its configuration and dependency graph as context.'],
    tr: ['AI Analiz', 'Bir kaynak seçip sorun — analiz, yapılandırmasını ve bağımlılık grafiğini bağlam olarak alır.'] },
  { id: 'gslb', cat: 'lb',
    en: ['GSLB', 'DNS-based global load balancing with health-checked records and node topology.'],
    tr: ['GSLB', 'Sağlık kontrollü kayıtlar ve node topolojisiyle DNS tabanlı global yük dengeleme.'] },
  { id: 'waf', cat: 'security',
    en: ['WAF Configurations', 'Coraza + OWASP CRS as an in-process Envoy WASM filter, with versioned rule configs.'],
    tr: ['WAF Yapılandırmaları', 'Envoy içinde WASM filtresi olarak Coraza + OWASP CRS; sürümlenen kural yapılandırmaları.'] },
  { id: 'acme', cat: 'security',
    en: ['ACME Certificates', 'Request Let’s Encrypt or Google Trust certificates over DNS-01, for the Envoy versions you choose.'],
    tr: ['ACME Sertifikaları', 'Seçtiğiniz Envoy sürümleri için DNS-01 ile Let’s Encrypt veya Google Trust sertifikası alın.'] },
];

export const shotSrc = (id, theme) => `/shots/${id}-${theme}.webp`;
export const shotById = Object.fromEntries(SHOTS.map(s => [s.id, s]));
