import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated sidebar: the docs/ folder taxonomy is the single source of truth.
// Adding a page = adding a file (+ sidebar_position frontmatter); category
// label/order/collapse live in each folder's _category_.json.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
